pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'armorchroma'

include('v121x', 'v261x', 'v262x')

project(':v121x').projectDir = file('versions/v121x')
project(':v261x').projectDir = file('versions/v261x')
project(':v262x').projectDir = file('versions/v262x')
